"""medicines table

Revision ID: 224fec62b536
Revises: a2e580f69eef
Create Date: 2024-10-16 11:47:43.900256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224fec62b536'
down_revision = 'a2e580f69eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('taking_start_date', sa.Date(), nullable=False),
    sa.Column('dose_per_day', sa.Float(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('taking_unit', sa.Enum('tablet', 'package', 'mg', 'drop', 'ml', name='takingunit'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicines')
    # ### end Alembic commands ###
