"""daily_logs table and daily_logs_details table

Revision ID: 392dde6bbda9
Revises: b0631f6f6c84
Create Date: 2024-11-04 14:36:21.735100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392dde6bbda9'
down_revision = 'b0631f6f6c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_log_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dose', sa.Float(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_id', 'daily_log_id', name='uq_medicine_daily_log')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_log_details')
    op.drop_table('daily_logs')
    # ### end Alembic commands ###
