"""added taking_timing column to medicine table

Revision ID: b0631f6f6c84
Revises: 224fec62b536
Create Date: 2024-10-28 10:16:59.385507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0631f6f6c84'
down_revision = '224fec62b536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taking_timing', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_column('taking_timing')

    # ### end Alembic commands ###
